### ISSUE TITLE
Source Class selection missing from item sheet

### ISSUE THREAD

**Issue by Nonstick-Panda** [kandashi/spellbook-assistant-manager#6]
I recently installed this module for a player who is multiclassing a few caster classes, however am having some issues.  The Source Class part of the item sheet is missing, and I receive a few errors in the console.  The below screenshot is a test performed in an entirely new/clean world with only this (and libWrapper) enabled.

Errors:
TypeError: Cannot read properties of undefined (reading 'split')
[Detected 1 package: spellbook-assistant-manager]
    at levelup.js:14:62
    at Hooks._call (foundry.js:294:14)
    at Hooks.call (foundry.js:279:33)
    at ActorSheet5eCharacter._render (foundry.js:3117:13)
    at async ActorSheet5eCharacter._render (foundry.js:3764:5)

TypeError: Cannot read properties of undefined (reading 'name')
[Detected 1 package: spellbook-assistant-manager]
    at levelup.js:28:119
    at Hooks._call (foundry.js:294:14)
    at Hooks.call (foundry.js:279:33)
    at ItemSheet5e._render (foundry.js:3117:13)
    at async ItemSheet5e._render (foundry.js:3764:5)

![image](https://user-images.githubusercontent.com/76752796/170503709-92434335-46d0-4090-b677-a9ffd47f1236.png)

**Comment by kandashi** [comment]
fixed

**Comment by MrPrimate** [comment]
I still get an error with the latest version, v0.2.01 installed

```
foundry.js:319 TypeError: Cannot read properties of undefined (reading 'sheetClass')
[Detected 1 package: spellbook-assistant-manager]
    at levelup.js:5:42
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at ActorSheet5eCharacter._render (foundry.js:3117:13)
    at async ActorSheet5eCharacter._render (foundry.js:3764:5)


foundry.js:319 TypeError: Cannot read properties of undefined (reading 'sheetClass')
[Detected 1 package: spellbook-assistant-manager]
    at levelup.js:57:42
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at ItemSheet5e._render (foundry.js:3117:13)
    at async ItemSheet5e._render (foundry.js:3764:5)

```
